### ISSUE TITLE
Minting assets not working properly (duplicate transactions)

### ISSUE THREAD

**Issue by cryptotester** [ProtonProtocol/nft-mint#1]
Tried to mint NFTs using this script. Looks promising, but I have the feeling that "await" is not really awaiting properly...
I had several problems running this as is:

when creating everything in one go, already at collection, schema or template level I get errors and must re-run the script.

Then after managing to create collection and schema and templates (and updating template_id manually) and proceeding to mint the NFTs also issues.

This one in particular:

```
{ Error: duplicate transaction [trx]
    at JsonRpc._callee$ (/node_modules/@proton/js/dist/js.cjs.development.js:5843:21)
    at tryCatch (/node_modules/@proton/js/dist/js.cjs.development.js:256:40)
    at Generator.invoke [as _invoke] (/node_modules/@proton/js/dist/js.cjs.development.js:486:22)
    at Generator.next (/node_modules/@proton/js/dist/js.cjs.development.js:311:21)
    at asyncGeneratorStep (/node_modules/@proton/js/dist/js.cjs.development.js:16:24)
    at _next (/node_modules/@proton/js/dist/js.cjs.development.js:38:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  json:
   { code: 409,
     message: 'Conflict',
     error:
      { code: 3040008,
        name: 'tx_duplicate',
        what: 'Duplicate transaction',
        details: [Array] } } }
```

I try to mind e.g. the first of a collection similar to the Dullahan, with max supply 10... and I can't even manage to mint 10 items without this duplicates errors. I have to call this many times.

Can you please re-test it?

I call it via:

`node index.js`

Node version: 10.19.0

**Comment by jafri** [comment]
When executing multiple TXs with the same data, you have to add 500ms between them

Try

async function wait (ms: number) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

await wait(500)
From: cryptotester ***@***.***>
Reply-To: ProtonProtocol/nft-mint ***@***.***>
Date: Saturday, March 27, 2021 at 10:28 AM
To: ProtonProtocol/nft-mint ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ProtonProtocol/nft-mint] Minting assets not working properly (duplicate transactions) (#1)

[△EXTERNAL]


Tried to mint NFTs using this script. Looks promising, but I have the feeling that "await" is not really awaiting properly...
I had several problems running this as is:

when creating everything in one go, already at collection, schema or template level I get errors and must re-run the script.

Then after managing to create collection and schema and templates (and updating template_id manually) and proceeding to mint the NFTs also issues.

This one in particular:

{ Error: duplicate transaction [trx]

    at JsonRpc._callee$ ***@***.***/js/dist/js.cjs.development.js:5843:21)

    at tryCatch ***@***.***/js/dist/js.cjs.development.js:256:40)

    at Generator.invoke [as _invoke] ***@***.***/js/dist/js.cjs.development.js:486:22)

    at Generator.next ***@***.***/js/dist/js.cjs.development.js:311:21)

    at asyncGeneratorStep ***@***.***/js/dist/js.cjs.development.js:16:24)

    at _next ***@***.***/js/dist/js.cjs.development.js:38:9)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  json:

   { code: 409,

     message: 'Conflict',

     error:

      { code: 3040008,

        name: 'tx_duplicate',

        what: 'Duplicate transaction',

        details: [Array] } } }

I try to mind e.g. the first of a collection similar to the Dullahan, with max supply 10... and I can't even manage to mint 10 items without this duplicates errors. I have to call this many times.

Can you please re-test it?

I call it via:

node index.js

Node version: 10.19.0

**Comment by cryptotester** [comment]
Thx for the reply. I tried inside of the loop, just after the transact. Still getting the duplicates errors. I tried like this:

```
await transact([
...
])

await wait(500)
```

Or maybe you meant to put the wait(500) somewhere else? Where?

I think at best there should be a counter for each template. (max_supply for each template)
Loop "infinite".
Don't use a manual 500 ms delay but rather put the transact call inside a try/catch to properly catch an exception.
Await should already wait for the call to be excecuted. I don't understand why it's an issue. It's async even if you explicitely await for it?
Increase the counter if no exception is thrown.
Stop the loop when the counter is reached.

Also I don't understand why it created duplicate transactions. I'd expect if I call a method 100 times, to be able to do that in parallel to gain time, each transaction should have a unique hash. I mean I'd expect to mint 100 NFTs in a couple of seconds (in parallel). Wouldn't this be possible?

**Comment by jafri** [comment]
Try a higher wait timer then, like 1000

It’s an issue because block times are 0.5s so if you submit the same TX in that timeframe, becomes a duplicate

Try with latest version

On Mar 27, 2021, at 11:47 AM, cryptotester ***@***.***> wrote:

﻿
[△EXTERNAL]



Thx for the reply. I tried inside of the loop, just after the transact. Still getting the duplicates errors. I tried like this:

await transact([
...
])

await wait(500)


I think at best there should be a counter for each template. (max_supply for each template)
Loop "infinite".
Don't use a manual 500 ms delay but rather put the transact call inside a try/catch to properly catch an exception.
Await should already wait for the call to be excecuted. I don't understand why it's an issue. It's async even if you explicitely await for it?
Increase the counter if no exception is thrown.
Stop the loop when the counter is reached.

Also I don't understand why it created duplicate transactions. I'd expect if I call a method 100 times, to be able to do that in parallel to gain time, each transaction should have a unique hash. I mean I'd expect to mint 100 NFTs in a couple of seconds (in parallel). Wouldn't this be possible?
